// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Export } from "./symbols";
import type { Symbol } from "./symbols";
import type { UnresolvedReference } from "./symbols";

export type ParseOutput = { symbols: Array<Symbol>, imports: Array<UnresolvedReference>, exports: Array<Export>, };
