// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./ids";
import type { SymbolMarker } from "./ids";

export type ByteOffset = number;

export type Export = { name: string, isReexport: boolean, source: string, };

export type Symbol = { id: Id<SymbolMarker, number>, kind: SymbolKind, name: string, range: TextRange, selectionRange: TextRange, bodyRange: TextRange | null, docstring: string, children: Array<Id<SymbolMarker, number>>, parent: Id<SymbolMarker, number> | null, signature: string, };

export type SymbolKind = "file" | "module" | "namespace" | "class" | "interface" | "enum" | "function" | "method" | "variable" | "const" | "typeAlias" | "property" | "parameter" | "unknown";

export type TextRange = { start: ByteOffset, end: ByteOffset, };

export type UnresolvedReference = { rawPath: string, symbols: string[], isTypeOnly: boolean, };
