// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleOptions } from "./bundler";

export type BundleRecord = { id: string, workspaceId: string, name: string, options: BundleOptions, createdAt: string, updatedAt: string, };

export type CloneBundleReq = { newName: string | null, };

export type CreateBundleReq = { workspaceId: string, name: string, options: BundleOptions, };

export type ListBundlesQuery = { limit: bigint | null, offset: bigint | null, };

export type UpdateBundlePayload = { name?: string | null, options: BundleOptions | null, };
