// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./ids";
import type { SymbolKind } from "./symbols";
import type { SymbolMarker } from "./ids";

export type BundleOptions = { rules: Array<RedactionRule>, targetFiles: Array<string>, hideBarrelExports: boolean, };

export type RedactionRule = { target: TargetScope, action: RedactionType, };

export type RedactionType = "removeEntirely" | "hideImplementation" | { "replaceWith": string };

/**
 * Defines *what* should be modified
 */
export type TargetScope = { "specificSymbol": { file_path: string, symbol_id: Id<SymbolMarker, number>, } } | { "entireFile": string } | { "global": SymbolKind };
