// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExplorerEntry = { "type": "file", "data": ExplorerFile } | { "type": "folder", "data": ExplorerFolder };

export type ExplorerFile = { name: string, path: string, size: bigint, extension: string, };

export type ExplorerFolder = { name: string, path: string, hasChildren: boolean, };
