// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Symbol } from "./symbols";

export type AxonGraphView = { nodes: Array<FileNodeView>, edges: Array<FileEdgeView>, };

export type FileEdgeView = { id: string, source: string, target: string, };

export type FileNodeView = { id: string, label: string, path: string, symbols: Array<Symbol>, imports: Array<string>, usedBy: Array<string>, };
