// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleOptions } from "./bundler";

export type StatelessGraphReq = { workspaceId: string, options: BundleOptions, };
