// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolId } from "./ids";

export type ByteOffset = number;

export type Export = { name: string, isReexport: boolean, source: string | null, };

export type Symbol = { id: SymbolId, kind: SymbolKind, name: string, 
/**
 * Full extent (docstring to end of block)
 */
range: TextRange, 
/**
 * Specifically where the name is defined (for clicking in UI)
 */
selectionRange: TextRange, 
/**
 * Implementation body { ... }
 */
bodyRange: TextRange | null, 
/**
 * Extracted documentation
 */
docstring: string | null, 
/**
 * Nested symbols (e.g. methods in a class)
 */
children: Array<SymbolId>, parent: SymbolId | null, 
/**
 * Pre-rendered signature for quick UI display
 */
signature: string | null, };

export type SymbolKind = "file" | "module" | "namespace" | "class" | "interface" | "enum" | "function" | "method" | "variable" | "const" | "typeAlias" | "property" | "parameter" | "unknown";

export type TextRange = { start: ByteOffset, end: ByteOffset, };

export type UnresolvedReference = { rawPath: string, symbols: Array<string>, isTypeOnly: boolean, };
