// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateWorkspaceReq = { name: string, projectRoot: string, };

export type DirQuery = { path: string, recursive: boolean, limit: number | null, };

export type FileQuery = { limit: number | null, };

export type ListWorkspacesQuery = { limit: bigint | null, offset: bigint | null, };

export type ReadFileReq = { path: string, };

export type SearchQuery = { value: string, limit: number | null, };

export type UpdateWorkspacePayload = { name: string | null, projectRoot: string | null, lastOpened: string | null, };

export type WorkspaceRecord = { id: string, ownerId: string, name: string, projectRoot: string, lastOpened: string, createdAt: string, updatedAt: string, };
