services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: axon-keycloak
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        /opt/keycloak/bin/kc.sh build --db=${POSTGRES_DB}
        
        /opt/keycloak/bin/kc.sh start \
          --optimized \
          --import-realm \
          --http-enabled=true \
          --hostname-backchannel-dynamic=true
    environment:
      KC_DB: ${POSTGRES_DB}
      KC_DB_URL: jdbc:postgresql://postgres:${PORT_PG_INTERNAL}/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_PROXY_HEADERS: xforwarded 
      KC_HTTP_ENABLED: "true"  
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
    volumes:
      - ../keycloak/realm-dev.json:/opt/keycloak/data/import/realm.json:ro
      - ../keycloak/themes:/opt/keycloak/themes:ro
    networks:
      - axon-network
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 3G