name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase repo name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push Axon Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/client-axon/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/client-axon:latest
 

      - name: Build and Push Axon Server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/axon-server/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/axon-server:latest

  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /root/axon-project
            # Pull the specific new images
            docker compose -f ./infra/docker-compose.prod.yaml pull
            # Apply changes
            docker compose -f ./infra/docker-compose.prod.yaml up -d --remove-orphans
